### ISSUE TITLE
This is the worst shit i have ever used in the production

### ISSUE THREAD

**Issue by lounah** [inFullMobile/InfullMvpAndroid#56]
It's awful. Why does the presenter know about view's fields? Unscalable crap, idk why r u guys using this. Bug fixing after u with ur infullmvp is painful. Ur dialog fragments are awful, ur open functions everywhere is shit, ur base-class-all-the-things is shit, ur dagger usage is shit. U should check modern android development techniques and remove this lib from being opensourced

**Comment by bhm** [comment]
Please submit either a PR with fixes propositions or submit a proper issue ticket.

**Comment by lounah** [comment]
that was just a cry of my heart sry

**Comment by bhm** [comment]
@Lounah the company has a blogpost about sacrifices and decisions made about this library. Signed under my name(, but written in the end collectively by all android developers of ifm at the time). What is not mentioned is the timeframe it was rolled out (mainly internally). Before `mockito-inline` (thus open functions), and right after Dagger 2.10 (which changed the setup quite significantly).

Keep in mind while most of the developers are no longer at ifm, some pop in from time to time. Please consider submitting a ticket with a problem, with as much details as possible.
